### ISSUE TITLE
The lemon-1.2.3 library fails to build on Mac 10.7.5

### ISSUE THREAD

**Issue by JensNRAD** [janelia-flyem/buildem#14]
The lemon-1.2.3 library fails to build on Mac 10.7.5 genrating this error message:

```
In file included from /Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/demo/graph_to_eps_demo.cc:34:
In file included from /Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/lemon/graph_to_eps.h:40:
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/lemon/bits/bezier.h:162:17: warning: 
      unused variable 'f' [-Wunused-variable]
    const Point f=(d+e)/2;
                ^
In file included from /Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/demo/graph_to_eps_demo.cc:34:
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/lemon/graph_to_eps.h:225:12: error: 
      dependent using declaration resolved to type without 'typename'
  using T::NodeTextColorType;
           ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/demo/graph_to_eps_demo.cc:85:3: note: 
      in instantiation of template class
      'lemon::GraphToEps<lemon::DefaultGraphToEpsTraits<lemon::ListDigraph>>'
      requested here
  graphToEps(g,"graph_to_eps_demo_out_1_pure.eps").
  ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/lemon/graph_to_eps.h:127:8: note: 
      target of using declaration
  enum NodeTextColorType
       ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/lemon/graph_to_eps.h:225:12: error: 
      dependent using declaration resolved to type without 'typename'
  using T::NodeTextColorType;
           ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/demo/graph_to_eps_demo.cc:93:5: note: 
      in instantiation of template class
      'lemon::GraphToEps<lemon::GraphToEps<lemon::DefaultGraphToEpsTraits<lemon::ListDigraph>>::CoordsTraits<lemon::DigraphExtender<lemon::ListDigraphBase>::NodeMap<lemon::dim2::Point<int>>>>'
      requested here
    coords(coords).
    ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/lemon/graph_to_eps.h:127:8: note: 
      target of using declaration
  enum NodeTextColorType
       ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/lemon/graph_to_eps.h:225:12: error: 
      dependent using declaration resolved to type without 'typename'
  using T::NodeTextColorType;
           ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/demo/graph_to_eps_demo.cc:110:5: note: 
      in instantiation of template class
      'lemon::GraphToEps<lemon::GraphToEps<lemon::DefaultGraphToEpsTraits<lemon::ListDigraph>>::NodeColorsTraits<lemon::ComposeMap<lemon::Palette,
      lemon::DigraphExtender<lemon::ListDigraphBase>::NodeMap<int>>>>' requested
      here
    nodeColors(composeMap(palette,colors)).
    ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/lemon/graph_to_eps.h:127:8: note: 
      target of using declaration
  enum NodeTextColorType
       ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/lemon/graph_to_eps.h:225:12: error: 
      dependent using declaration resolved to type without 'typename'
  using T::NodeTextColorType;
           ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/demo/graph_to_eps_demo.cc:137:5: note: 
      in instantiation of template class
      'lemon::GraphToEps<lemon::GraphToEps<lemon::DefaultGraphToEpsTraits<lemon::ListDigraph>>::NodeShapesTraits<lemon::DigraphExtender<lemon::ListDigraphBase>::NodeMap<int>>>'
      requested here
    nodeShapes(shapes).
    ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/lemon/graph_to_eps.h:127:8: note: 
      target of using declaration
  enum NodeTextColorType
       ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/lemon/graph_to_eps.h:225:12: error: 
      dependent using declaration resolved to type without 'typename'
  using T::NodeTextColorType;
           ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/demo/graph_to_eps_demo.cc:152:18: note: 
      in instantiation of template class
      'lemon::GraphToEps<lemon::GraphToEps<lemon::DefaultGraphToEpsTraits<lemon::ListDigraph>>::NodeSizesTraits<lemon::DigraphExtender<lemon::ListDigraphBase>::NodeMap<double>>>'
      requested here
    nodeScale(2).nodeSizes(sizes).
                 ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/lemon/graph_to_eps.h:127:8: note: 
      target of using declaration
  enum NodeTextColorType
       ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/lemon/graph_to_eps.h:225:12: error: 
      dependent using declaration resolved to type without 'typename'
  using T::NodeTextColorType;
           ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/demo/graph_to_eps_demo.cc:170:5: note: 
      in instantiation of template class
      'lemon::GraphToEps<lemon::GraphToEps<lemon::GraphToEps<lemon::DefaultGraphToEpsTraits<lemon::ListDigraph>>::NodeSizesTraits<lemon::DigraphExtender<lemon::ListDigraphBase>::NodeMap<double>>>::CoordsTraits<lemon::DigraphExtender<lemon::ListDigraphBase>::NodeMap<lemon::dim2::Point<int>>>>'
      requested here
    coords(coords).
    ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/lemon/graph_to_eps.h:127:8: note: 
      target of using declaration
  enum NodeTextColorType
       ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/lemon/graph_to_eps.h:225:12: error: 
      dependent using declaration resolved to type without 'typename'
  using T::NodeTextColorType;
           ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/demo/graph_to_eps_demo.cc:201:5: note: 
      in instantiation of template class
      'lemon::GraphToEps<lemon::GraphToEps<lemon::GraphToEps<lemon::DefaultGraphToEpsTraits<lemon::ListDigraph>>::CoordsTraits<lemon::DigraphExtender<lemon::ListDigraphBase>::NodeMap<lemon::dim2::Point<int>>>>::NodeTextsTraits<lemon::DigraphExtender<lemon::ListDigraphBase>::NodeMap<int>>>'
      requested here
    nodeTexts(hcolors).nodeTextSize(.6).
    ^
/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3/lemon/graph_to_eps.h:127:8: note: 
      target of using declaration
  enum NodeTextColorType
       ^
1 warning and 7 errors generated.
make[5]: *** [demo/CMakeFiles/graph_to_eps_demo.dir/graph_to_eps_demo.cc.o] Error 1
make[4]: *** [demo/CMakeFiles/graph_to_eps_demo.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [/Volumes/SSD/ilastik/buildem/src/lemon-1.2.3-stamp/lemon-1.2.3-build] Error 2
make[1]: *** [CMakeFiles/lemon-1.2.3.dir/all] Error 2
make: *** [all] Error 2
```
